#!/bin/bash

./prepJob

$PETSC_DIR/arch-darwin-c-opt/bin/mpiexec -np 4 ./mops \
        -numtracers 9 \
        -i po4ini.petsc,dopini.petsc,oxyini.petsc,phyini.petsc,zooini.petsc,detini.petsc,no3ini.petsc,dicini.petsc,alkini.petsc \
        -me Ae \
        -mi Ai \
        -t0 0.0 -iter0 0 \
        -deltat_clock 0.0013888888888889 \
        -max_steps 10 \
        -write_steps 10 \
        -o po4.petsc,dop.petsc,oxy.petsc,phy.petsc,zoo.petsc,det.petsc,no3.petsc,dic.petsc,alk.petsc \
        -external_forcing \
        -use_profiles \
        -nzeuph 2 \
        -biogeochem_deltat 43200.0 \
        -burial_sum_steps 10 \
        -calc_misfit -misfit_file misfit_output.txt -average_cost -cost_start_time_step 1 -cost_time_steps 10 \
                -periodic_matrix -matrix_cycle_period 1.0 \
                -matrix_cycle_step 0.0833333333333333 \
                -periodic_biogeochem_forcing \
                -periodic_biogeochem_cycle_period 1.0 \
                -periodic_biogeochem_cycle_step 0.08333333333333 \
                -num_biogeochem_steps_per_ocean_step 8 \
        -bgc_params_file parameters_input.txt -bgc_paramnames_file parameters_names.txt -num_bgc_params_file num_bgc_params.txt \
        -separate_biogeochem_time_stepping \
        -time_avg -avg_start_time_step 1 -avg_time_steps 10 \
        -avg_files po4avg.petsc,dopavg.petsc,oxyavg.petsc,phyavg.petsc,zooavg.petsc,detavg.petsc,no3avg.petsc,dicavg.petsc,alkavg.petsc \
        -calc_diagnostics -diag_start_time_step 1 -diag_time_steps 10 \
        -diag_files fbgc1.petsc,fbgc2.petsc,fbgc3.petsc,fbgc4.petsc,fbgc5.petsc,fbgc6.petsc,fbgc7.petsc \
        -mask_files PO4_amask.petsc,O2_amask.petsc,NO3_amask.petsc \
        -obs_files po4_obs.petsc,o2_obs.petsc,no3_obs.petsc \
        -num_mask_regions 19,19,19 \
        > log

./cleanJob
      
# driver options:
#  I/O:
#   -pickup_out pickup.petsc \
#   -time_file output_time.txt \
#  circulation-specific options:
#   add this option for configurations in which the forcing is rescaled because of a time-varying free surface:
#    -rescale_forcing_file Rfs \
# model-specific options:
