#!/bin/bash
#PBS -o serial.out
#PBS -j oe
#PBS -l walltime=00:15:00
#PBS -N serial
#PBS -l nodes=1:ppn=1
#PBS -q mpp1testq
#PBS -A shk00025

cd $PBS_O_WORKDIR

maxIter=$(head -5 nIter.txt | tail -1 | awk '{print $1}')
nIter=$(tail -1 nIter.txt | awk '{print $1}')
terminate=$(tail -1 nIter.txt | awk '{print $3}')

aprun -B ./cmaes $nIter nIter.txt > serial_$nIter.log

if [ "$?" -eq 0 ]; then
	if [ "$nIter" -lt "$maxIter" ]; then
		if [ "$terminate" -lt 1 ]; then
			msub parallel.job
		fi
	fi
fi
