#!/bin/bash
# #SBATCH --nodes=1
# #SBATCH --ntasks-per-node=1
# #SBATCH --time=00:00:30

./prepJob
./runtest
./cleanJob

# clang create_obs.c -o create_obs
# clang runtest.c -o runtest
# ./create_obs
