#!/bin/bash

mv ../*_*.txt .
cp -p ../nIter.txt .

./prepJob

maxIter=$(head -5 ../nIter.txt | tail -1 | awk '{print $1}')
nIter=$(tail -1 ../nIter.txt | awk '{print $1}')
numSessions=$(head -4 ../nIter.txt | tail -1 | awk '{print $1}')
for nSession in $(seq 1 $numSessions)
do 

	$PETSC_DIR/arch-darwin-c-opt/bin/mpiexec -np 4 ./mops \
        -numtracers 9 \
        -i po4ini.petsc,dopini.petsc,oxyini.petsc,phyini.petsc,zooini.petsc,detini.petsc,no3ini.petsc,dicini.petsc,alkini.petsc \
        -me Ae \
        -mi Ai \
        	-pickup_out "pickup_"$nIter"_"$nSession".petsc" \
        	-pickup_runoff_out "pickup_runoff_"$nIter"_"$nSession".bin" \
        	-time_file "output_time_"$nSession".txt" \
        -t0 0.0 -iter0 0 \
        -deltat_clock 0.0013888888888889 \
        -max_steps 10 \
        -write_steps 10 \
        -o "po4_"$nSession".petsc","dop_"$nSession".petsc","oxy_"$nSession".petsc","phy_"$nSession".petsc","zoo_"$nSession".petsc","det_"$nSession".petsc","no3_"$nSession".petsc","dic_"$nSession".petsc","alk_"$nSession".petsc" \
        -external_forcing \
        -use_profiles \
        -nzeuph 2 \
        -biogeochem_deltat 43200.0 \
        -burial_sum_steps 10 \
        -calc_misfit -misfit_file "misfit_output_"$nIter"_"$nSession".txt" -average_cost -cost_start_time_step 1 -cost_time_steps 10 \
                -periodic_matrix -matrix_cycle_period 1.0 \
                -matrix_cycle_step 0.0833333333333333 \
                -periodic_biogeochem_forcing \
                -periodic_biogeochem_cycle_period 1.0 \
                -periodic_biogeochem_cycle_step 0.08333333333333 \
                -num_biogeochem_steps_per_ocean_step 8 \
        -bgc_params_file "parameters_input_"$nIter"_"$nSession".txt" -bgc_paramnames_file parameters_names.txt -num_bgc_params_file num_bgc_params.txt \
        -separate_biogeochem_time_stepping \
        -time_avg -avg_start_time_step 1 -avg_time_steps 10 \
        -avg_files "po4avg_"$nIter"_"$nSession".petsc","dopavg_"$nIter"_"$nSession".petsc","oxyavg_"$nIter"_"$nSession".petsc","phyavg_"$nIter"_"$nSession".petsc","zooavg_"$nIter"_"$nSession".petsc","detavg_"$nIter"_"$nSession".petsc","no3avg_"$nIter"_"$nSession".petsc","dicavg_"$nIter"_"$nSession".petsc","alkavg_"$nIter"_"$nSession".petsc" \
        -calc_diagnostics -diag_start_time_step 1 -diag_time_steps 10 \
        -diag_files "fbgc1_"$nIter"_"$nSession".petsc","fbgc2_"$nIter"_"$nSession".petsc","fbgc3_"$nIter"_"$nSession".petsc","fbgc4_"$nIter"_"$nSession".petsc","fbgc5_"$nIter"_"$nSession".petsc","fbgc6_"$nIter"_"$nSession".petsc","fbgc7_"$nIter"_"$nSession".petsc" \
        -mask_files PO4_amask.petsc,O2_amask.petsc,NO3_amask.petsc \
        -obs_files po4_obs_twin6.petsc,o2_obs_twin6.petsc,no3_obs_twin6.petsc \
        -num_mask_regions 19,19,19 \
        > "log_"$nIter"_"$nSession

done

cp -p nIter.txt ../.

./cleanJob
      
# driver options:
#  I/O:
#   -pickup_out pickup.petsc \
#   -time_file output_time.txt \
#  circulation-specific options:
#   add this option for configurations in which the forcing is rescaled because of a time-varying free surface:
#    -rescale_forcing_file Rfs \
# model-specific options:
